app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

$api = app('Dingo\Api\Routing\Router');
//
// Route::get('/', function () {
//     return view('welcome');
// });

// Route::auth();

// Authentication Routes...
// Route::post('login', 'Auth\AuthController@login');
Route::get('logout', 'LoginController@logout');
Route::get('login', 'LoginController@getLogin');
Route::post('login', [ 'as' => 'login', 'uses' => 'LoginController@validateCredentials']);

// Route::post('login', 'LoginController@validateCredentials');

// Registration Routes...
// Route::get('register', 'Auth\AuthController@showRegistrationForm');
// Route::post('register', 'Auth\AuthController@register');

// Password Reset Routes...
Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
Route::post('password/reset', 'Auth\PasswordController@reset');

// Web Routes //

Route::get('/', 'Dashboard@index');

Route::get('categories/posterchange', 'CategoryController@posterchange');
Route::get('artists/posterchange', "ArtistController@posterchange");
Route::resource("categories","CategoryController",
                ['only' => ['index', 'show']]);
Route::resource("artists","ArtistController",
                ['only' => ['index', 'show']]);
Route::resource("cultures","CultureController",
                ['only' => ['index', 'show']]);
Route::resource("favourites","FavouriteController");
Route::resource("media","MediumController",
                ['only' => ['index', 'show']]);
// Route::resource("objectcategories","ObjectcategoryController");
// Route::resource("objectartists","ObjectartistController");
Route::resource("galleries","ObjectController",
                ['only' => ['index', 'show']]);


// Route::get('map', 'MappingController@map');
// Route::resource("main_categories","MainCategoryController");
Route::resource("m_main_categories","MMainCategoryController"); // Add this line in routes.php
Route::get('appheadings/postsequesnce', 'AppheadingController@postsequesnce');
Route::get('appheadings/appheadings', 'AppheadingController@appheadings');
Route::post('appheadings/updatedetails', 'AppheadingController@updatedetails');
Route::resource("appheadings","AppheadingController");

// Route::get('artist/posterchange', 'ArtistController@posterchange');
// Route::get('artist/posterchange', 'ArtistController@posterchange');
// Route::resource("server_details","ServerDetailController");
// Route::resource("galleries","GalleryController");
// Route::resource("main_categories","MainCategoryController");
// Route::resource("cultures","CultureController");
// Route::resource("categories","CategoryController");
// Route::resource("app_details","AppDetailController");
// Route::resource("artists","ArtistController");
// Route::resource("favorites","FavoriteController");
// Route::resource("basic_auths","BasicAuthController");
// Route::resource("post_categories","PostCategoryController");
//
// Route::get("cultures","PostCategoryController@cultures_index");
// Route::get("artists","PostCategoryController@artists_index");
// Route::get("categories","PostCategoryController@categories_index");



// API Routes //

// $api->version('v1', function ($api) {
//
//   $api->get('maincategory/','App\Api\v1\Controllers\MainCategoryapi@index')->middleware('auth.admin');
//   $api->get('subcategory/data_by_id','App\Api\v1\Controllers\SubCategoryapi@all_by_id')->middleware('auth.admin');
//   $api->get('galleries','App\Api\v1\Controllers\Galleryapi@index')->middleware('auth.admin');
//   $api->get('galleries/by_subcategory','App\Api\v1\Controllers\SubCategoryapi@subcategories_gallery_by_id')->middleware('auth.admin');
//   $api->get('galleries/gallery_search','App\Api\v1\Controllers\Galleryapi@gallery_search')->middleware('auth.admin');
//   $api->get('galleries/all_subcategory','App\Api\v1\Controllers\Galleryapi@all_subcategory')->middleware('auth.admin');
//   $api->post('favorites','App\Api\v1\Controllers\Favoriteapi@store')->middleware('auth.admin');
//   $api->get('favorites/userfavorite','App\Api\v1\Controllers\Favoriteapi@user_favorite')->middleware('auth.admin');
//   $api->post('users/login','App\Api\v1\Controllers\Userapi@login')->middleware('auth.admin');
//   $api->get('users/logout','App\Api\v1\Controllers\Userapi@logout')->middleware('auth.admin');
//   $api->post('users/','App\Api\v1\Controllers\Userapi@storeapi')->middleware('auth.admin');
//
//
//
//
//   // $api->post('galleries','App\Api\v1\Controllers\Galleryapi@store')->middleware('auth.admin');
//   // $api->get('galleries/by_artist','App\Api\v1\Controllers\Galleryapi@by_artist')->middleware('auth.admin');
//   // $api->get('galleries/by_category','App\Api\v1\Controllers\Galleryapi@by_category')->middleware('auth.admin');
//   // $api->get('galleries/by_culture','App\Api\v1\Controllers\Galleryapi@by_culture')->middleware('auth.admin');
//
//
//
//
//   $api->get('galleries/{gallery_id}','App\Api\v1\Controllers\Galleryapi@show')->middleware('auth.admin');
//   $api->get('subcategory/{subcategory_id}','App\Api\v1\Controllers\SubCategoryapi@show')->middleware('auth.admin');
//   // $api->get('artists/','App\Api\v1\Controllers\Artistapi@index')->middleware('auth.admin');
//   // $api->get('cultures/','App\Api\v1\Controllers\Cultureapi@index')->middleware('auth.admin');
//   // $api->get('categories/','App\Api\v1\Controllers\Categoryapi@index')->middleware('auth.admin');
//   // $api->get('artists/{artist_id}','App\Api\v1\Controllers\Artistapi@show')->middleware('auth.admin');
//   // $api->get('cultures/{culture_id}','App\Api\v1\Controllers\Cultureapi@show')->middleware('auth.admin');
//   // $api->get('categories/{category_id}','App\Api\v1\Controllers\Categoryapi@show')->middleware('auth.admin');
//
//
// });

app/Culture.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Culture extends Model
{
    //
}

app/Http/Controllers/CultureController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use DB;
use App\Culture;
use Illuminate\Http\Request;

class CultureController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$cultures = DB::statement('CALL GetCultures');
		return compact('cultures');die;
		return view('cultures.index', compact('cultures'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	 
	public function create()
	{
		return view('cultures.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$culture = new Culture();

		$culture->name = $request->input("name");

		$culture->save();

		return redirect()->route('cultures.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$culture = Culture::findOrFail($id);

		return view('cultures.show', compact('culture'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$culture = Culture::findOrFail($id);

		return view('cultures.edit', compact('culture'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$culture = Culture::findOrFail($id);

		$culture->name = $request->input("name");

		$culture->save();

		return redirect()->route('cultures.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$culture = Culture::findOrFail($id);
		$culture->delete();

		return redirect()->route('cultures.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/cultures/create.blade.php
@extends('layouts.app')
@section('content')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
<div class="right_col" role="main">

    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Cultures / Create </h1>
    </div>

    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('cultures.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ old("name") }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('cultures.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
  </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/cultures/edit.blade.php
@extends('layouts.app')
@section('content')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection

<div class="right_col" role="main">

    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Cultures / Edit #{{$culture->id}}</h1>
    </div>

    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('cultures.update', $culture->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ is_null(old("name")) ? $culture->name : old("name") }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('cultures.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
  </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/cultures/index.blade.php
@extends('layouts.app')
@section('content')

<div class="right_col" role="main">

    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Cultures
            <a class="btn btn-success pull-right" href="{{ route('cultures.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>

    <div class="row">
        <div class="col-md-12">
            @if($cultures->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>NAME</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($cultures as $culture)
                            <tr>
                                <td>{{$culture->id}}</td>
                                <td>{{$culture->name}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('cultures.show', $culture->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('cultures.edit', $culture->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('cultures.destroy', $culture->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $cultures->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>
  </div>

@endsection

resources/views/cultures/show.blade.php
@extends('layouts.app')
@section('content')
<div class="right_col" role="main">

<div class="page-header">
        <h1>Cultures / Show #{{$culture->id}}</h1>
        <form action="{{ route('cultures.destroy', $culture->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('cultures.edit', $culture->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>

    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="name">NAME</label>
                     <p class="form-control-static">{{$culture->name}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('cultures.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>
  </div>

@endsection