app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

$api = app('Dingo\Api\Routing\Router');
//
// Route::get('/', function () {
//     return view('welcome');
// });

// Route::auth();

// Authentication Routes...
// Route::post('login', 'Auth\AuthController@login');
Route::get('logout', 'LoginController@logout');
Route::get('login', 'LoginController@getLogin');
Route::post('login', [ 'as' => 'login', 'uses' => 'LoginController@validateCredentials']);

// Route::post('login', 'LoginController@validateCredentials');

// Registration Routes...
// Route::get('register', 'Auth\AuthController@showRegistrationForm');
// Route::post('register', 'Auth\AuthController@register');

// Password Reset Routes...
Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
Route::post('password/reset', 'Auth\PasswordController@reset');

// Web Routes //

Route::get('/', 'Dashboard@index');

Route::get('categories/posterchange', 'CategoryController@posterchange');
Route::get('artists/posterchange', "ArtistController@posterchange");
Route::resource("categories","CategoryController",
                ['only' => ['index', 'show']]);
Route::resource("artists","ArtistController",
                ['only' => ['index', 'show']]);
Route::resource("cultures","CultureController",
                ['only' => ['index', 'show']]);
Route::resource("favourites","FavouriteController");
Route::resource("media","MediumController",
                ['only' => ['index', 'show']]);
// Route::resource("objectcategories","ObjectcategoryController");
// Route::resource("objectartists","ObjectartistController");
Route::resource("galleries","ObjectController",
                ['only' => ['index', 'show']]);


// Route::get('map', 'MappingController@map');
// Route::resource("main_categories","MainCategoryController");
Route::resource("m_main_categories","MMainCategoryController"); // Add this line in routes.php
Route::get('appheadings/postsequesnce', 'AppheadingController@postsequesnce');
Route::get('appheadings/appheadings', 'AppheadingController@appheadings');
Route::post('appheadings/updatedetails', 'AppheadingController@updatedetails');
Route::resource("appheadings","AppheadingController");

// Route::get('artist/posterchange', 'ArtistController@posterchange');
// Route::get('artist/posterchange', 'ArtistController@posterchange');
// Route::resource("server_details","ServerDetailController");
// Route::resource("galleries","GalleryController");
// Route::resource("main_categories","MainCategoryController");
// Route::resource("cultures","CultureController");
// Route::resource("categories","CategoryController");
// Route::resource("app_details","AppDetailController");
// Route::resource("artists","ArtistController");
// Route::resource("favorites","FavoriteController");
// Route::resource("basic_auths","BasicAuthController");
// Route::resource("post_categories","PostCategoryController");
//
// Route::get("cultures","PostCategoryController@cultures_index");
// Route::get("artists","PostCategoryController@artists_index");
// Route::get("categories","PostCategoryController@categories_index");



// API Routes //

// $api->version('v1', function ($api) {
//
//   $api->get('maincategory/','App\Api\v1\Controllers\MainCategoryapi@index')->middleware('auth.admin');
//   $api->get('subcategory/data_by_id','App\Api\v1\Controllers\SubCategoryapi@all_by_id')->middleware('auth.admin');
//   $api->get('galleries','App\Api\v1\Controllers\Galleryapi@index')->middleware('auth.admin');
//   $api->get('galleries/by_subcategory','App\Api\v1\Controllers\SubCategoryapi@subcategories_gallery_by_id')->middleware('auth.admin');
//   $api->get('galleries/gallery_search','App\Api\v1\Controllers\Galleryapi@gallery_search')->middleware('auth.admin');
//   $api->get('galleries/all_subcategory','App\Api\v1\Controllers\Galleryapi@all_subcategory')->middleware('auth.admin');
//   $api->post('favorites','App\Api\v1\Controllers\Favoriteapi@store')->middleware('auth.admin');
//   $api->get('favorites/userfavorite','App\Api\v1\Controllers\Favoriteapi@user_favorite')->middleware('auth.admin');
//   $api->post('users/login','App\Api\v1\Controllers\Userapi@login')->middleware('auth.admin');
//   $api->get('users/logout','App\Api\v1\Controllers\Userapi@logout')->middleware('auth.admin');
//   $api->post('users/','App\Api\v1\Controllers\Userapi@storeapi')->middleware('auth.admin');
//
//
//
//
//   // $api->post('galleries','App\Api\v1\Controllers\Galleryapi@store')->middleware('auth.admin');
//   // $api->get('galleries/by_artist','App\Api\v1\Controllers\Galleryapi@by_artist')->middleware('auth.admin');
//   // $api->get('galleries/by_category','App\Api\v1\Controllers\Galleryapi@by_category')->middleware('auth.admin');
//   // $api->get('galleries/by_culture','App\Api\v1\Controllers\Galleryapi@by_culture')->middleware('auth.admin');
//
//
//
//
//   $api->get('galleries/{gallery_id}','App\Api\v1\Controllers\Galleryapi@show')->middleware('auth.admin');
//   $api->get('subcategory/{subcategory_id}','App\Api\v1\Controllers\SubCategoryapi@show')->middleware('auth.admin');
//   // $api->get('artists/','App\Api\v1\Controllers\Artistapi@index')->middleware('auth.admin');
//   // $api->get('cultures/','App\Api\v1\Controllers\Cultureapi@index')->middleware('auth.admin');
//   // $api->get('categories/','App\Api\v1\Controllers\Categoryapi@index')->middleware('auth.admin');
//   // $api->get('artists/{artist_id}','App\Api\v1\Controllers\Artistapi@show')->middleware('auth.admin');
//   // $api->get('cultures/{culture_id}','App\Api\v1\Controllers\Cultureapi@show')->middleware('auth.admin');
//   // $api->get('categories/{category_id}','App\Api\v1\Controllers\Categoryapi@show')->middleware('auth.admin');
//
//
// });

app/Favourite.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Favourite extends Model
{
    //
}

app/Http/Controllers/FavouriteController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Favourite;
use Illuminate\Http\Request;

class FavouriteController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$favourites = Favourite::orderBy('id', 'desc')->paginate(10);

		return view('favourites.index', compact('favourites'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('favourites.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$favourite = new Favourite();

		$favourite->object_id = $request->input("object_id");
        $favourite->media_master_id = $request->input("media_master_id");
        $favourite->user_id = $request->input("user_id");

		$favourite->save();

		return redirect()->route('favourites.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$favourite = Favourite::findOrFail($id);

		return view('favourites.show', compact('favourite'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$favourite = Favourite::findOrFail($id);

		return view('favourites.edit', compact('favourite'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$favourite = Favourite::findOrFail($id);

		$favourite->object_id = $request->input("object_id");
        $favourite->media_master_id = $request->input("media_master_id");
        $favourite->user_id = $request->input("user_id");

		$favourite->save();

		return redirect()->route('favourites.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$favourite = Favourite::findOrFail($id);
		$favourite->delete();

		return redirect()->route('favourites.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/favourites/create.blade.php
@extends('layouts.app')
@section('content')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
<div class="right_col" role="main">

    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Favourites / Create </h1>
    </div>


    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('favourites.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('object_id')) has-error @endif">
                       <label for="object_id-field">Object_id</label>
                    <input type="text" id="object_id-field" name="object_id" class="form-control" value="{{ old("object_id") }}"/>
                       @if($errors->has("object_id"))
                        <span class="help-block">{{ $errors->first("object_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('media_master_id')) has-error @endif">
                       <label for="media_master_id-field">Media_master_id</label>
                    <input type="text" id="media_master_id-field" name="media_master_id" class="form-control" value="{{ old("media_master_id") }}"/>
                       @if($errors->has("media_master_id"))
                        <span class="help-block">{{ $errors->first("media_master_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('user_id')) has-error @endif">
                       <label for="user_id-field">User_id</label>
                    <input type="text" id="user_id-field" name="user_id" class="form-control" value="{{ old("user_id") }}"/>
                       @if($errors->has("user_id"))
                        <span class="help-block">{{ $errors->first("user_id") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('favourites.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
  </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/favourites/edit.blade.php
@extends('layouts.app')
@section('content')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
<div class="right_col" role="main">

    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Favourites / Edit #{{$favourite->id}}</h1>
    </div>

    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('favourites.update', $favourite->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('object_id')) has-error @endif">
                       <label for="object_id-field">Object_id</label>
                    <input type="text" id="object_id-field" name="object_id" class="form-control" value="{{ is_null(old("object_id")) ? $favourite->object_id : old("object_id") }}"/>
                       @if($errors->has("object_id"))
                        <span class="help-block">{{ $errors->first("object_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('media_master_id')) has-error @endif">
                       <label for="media_master_id-field">Media_master_id</label>
                    <input type="text" id="media_master_id-field" name="media_master_id" class="form-control" value="{{ is_null(old("media_master_id")) ? $favourite->media_master_id : old("media_master_id") }}"/>
                       @if($errors->has("media_master_id"))
                        <span class="help-block">{{ $errors->first("media_master_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('user_id')) has-error @endif">
                       <label for="user_id-field">User_id</label>
                    <input type="text" id="user_id-field" name="user_id" class="form-control" value="{{ is_null(old("user_id")) ? $favourite->user_id : old("user_id") }}"/>
                       @if($errors->has("user_id"))
                        <span class="help-block">{{ $errors->first("user_id") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('favourites.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
  </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/favourites/index.blade.php
@extends('layouts.app')
@section('content')

<div class="right_col" role="main">

    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Favourites
            <a class="btn btn-success pull-right" href="{{ route('favourites.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>

    <div class="row">
        <div class="col-md-12">
            @if($favourites->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>OBJECT_ID</th>
                        <th>MEDIA_MASTER_ID</th>
                        <th>USER_ID</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($favourites as $favourite)
                            <tr>
                                <td>{{$favourite->id}}</td>
                                <td>{{$favourite->object_id}}</td>
                    <td>{{$favourite->media_master_id}}</td>
                    <td>{{$favourite->user_id}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('favourites.show', $favourite->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('favourites.edit', $favourite->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('favourites.destroy', $favourite->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $favourites->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>
</div>
@endsection

resources/views/favourites/show.blade.php
@extends('layouts.app')
@section('content')

<div class="right_col" role="main">

<div class="page-header">
        <h1>Favourites / Show #{{$favourite->id}}</h1>
        <form action="{{ route('favourites.destroy', $favourite->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('favourites.edit', $favourite->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>

    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="object_id">OBJECT_ID</label>
                     <p class="form-control-static">{{$favourite->object_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="media_master_id">MEDIA_MASTER_ID</label>
                     <p class="form-control-static">{{$favourite->media_master_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="user_id">USER_ID</label>
                     <p class="form-control-static">{{$favourite->user_id}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('favourites.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>
  </div>

@endsection