app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

$api = app('Dingo\Api\Routing\Router');
//
// Route::get('/', function () {
//     return view('welcome');
// });

// Route::auth();

// Authentication Routes...
// Route::post('login', 'Auth\AuthController@login');
Route::get('logout', 'LoginController@logout');
Route::get('login', 'LoginController@getLogin');
Route::post('login', [ 'as' => 'login', 'uses' => 'LoginController@validateCredentials']);

// Route::post('login', 'LoginController@validateCredentials');

// Registration Routes...
// Route::get('register', 'Auth\AuthController@showRegistrationForm');
// Route::post('register', 'Auth\AuthController@register');

// Password Reset Routes...
Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
Route::post('password/reset', 'Auth\PasswordController@reset');

// Web Routes //

Route::get('/', 'Dashboard@index');

Route::get('categories/posterchange', 'CategoryController@posterchange');
Route::get('artists/posterchange', "ArtistController@posterchange");
Route::resource("categories","CategoryController",
                ['only' => ['index', 'show']]);
Route::resource("artists","ArtistController",
                ['only' => ['index', 'show']]);
Route::resource("cultures","CultureController",
                ['only' => ['index', 'show']]);
Route::resource("favourites","FavouriteController");
Route::resource("media","MediumController",
                ['only' => ['index', 'show']]);
// Route::resource("objectcategories","ObjectcategoryController");
// Route::resource("objectartists","ObjectartistController");
Route::resource("galleries","ObjectController",
                ['only' => ['index', 'show']]);


// Route::get('map', 'MappingController@map');
// Route::resource("main_categories","MainCategoryController");
Route::resource("m_main_categories","MMainCategoryController"); // Add this line in routes.php
Route::get('appheadings/postsequesnce', 'AppheadingController@postsequesnce');
Route::get('appheadings/appheadings', 'AppheadingController@appheadings');
Route::post('appheadings/updatedetails', 'AppheadingController@updatedetails');
Route::resource("appheadings","AppheadingController");

// Route::get('artist/posterchange', 'ArtistController@posterchange');
// Route::get('artist/posterchange', 'ArtistController@posterchange');
// Route::resource("server_details","ServerDetailController");
// Route::resource("galleries","GalleryController");
// Route::resource("main_categories","MainCategoryController");
// Route::resource("cultures","CultureController");
// Route::resource("categories","CategoryController");
// Route::resource("app_details","AppDetailController");
// Route::resource("artists","ArtistController");
// Route::resource("favorites","FavoriteController");
// Route::resource("basic_auths","BasicAuthController");
// Route::resource("post_categories","PostCategoryController");
//
// Route::get("cultures","PostCategoryController@cultures_index");
// Route::get("artists","PostCategoryController@artists_index");
// Route::get("categories","PostCategoryController@categories_index");



// API Routes //

// $api->version('v1', function ($api) {
//
//   $api->get('maincategory/','App\Api\v1\Controllers\MainCategoryapi@index')->middleware('auth.admin');
//   $api->get('subcategory/data_by_id','App\Api\v1\Controllers\SubCategoryapi@all_by_id')->middleware('auth.admin');
//   $api->get('galleries','App\Api\v1\Controllers\Galleryapi@index')->middleware('auth.admin');
//   $api->get('galleries/by_subcategory','App\Api\v1\Controllers\SubCategoryapi@subcategories_gallery_by_id')->middleware('auth.admin');
//   $api->get('galleries/gallery_search','App\Api\v1\Controllers\Galleryapi@gallery_search')->middleware('auth.admin');
//   $api->get('galleries/all_subcategory','App\Api\v1\Controllers\Galleryapi@all_subcategory')->middleware('auth.admin');
//   $api->post('favorites','App\Api\v1\Controllers\Favoriteapi@store')->middleware('auth.admin');
//   $api->get('favorites/userfavorite','App\Api\v1\Controllers\Favoriteapi@user_favorite')->middleware('auth.admin');
//   $api->post('users/login','App\Api\v1\Controllers\Userapi@login')->middleware('auth.admin');
//   $api->get('users/logout','App\Api\v1\Controllers\Userapi@logout')->middleware('auth.admin');
//   $api->post('users/','App\Api\v1\Controllers\Userapi@storeapi')->middleware('auth.admin');
//
//
//
//
//   // $api->post('galleries','App\Api\v1\Controllers\Galleryapi@store')->middleware('auth.admin');
//   // $api->get('galleries/by_artist','App\Api\v1\Controllers\Galleryapi@by_artist')->middleware('auth.admin');
//   // $api->get('galleries/by_category','App\Api\v1\Controllers\Galleryapi@by_category')->middleware('auth.admin');
//   // $api->get('galleries/by_culture','App\Api\v1\Controllers\Galleryapi@by_culture')->middleware('auth.admin');
//
//
//
//
//   $api->get('galleries/{gallery_id}','App\Api\v1\Controllers\Galleryapi@show')->middleware('auth.admin');
//   $api->get('subcategory/{subcategory_id}','App\Api\v1\Controllers\SubCategoryapi@show')->middleware('auth.admin');
//   // $api->get('artists/','App\Api\v1\Controllers\Artistapi@index')->middleware('auth.admin');
//   // $api->get('cultures/','App\Api\v1\Controllers\Cultureapi@index')->middleware('auth.admin');
//   // $api->get('categories/','App\Api\v1\Controllers\Categoryapi@index')->middleware('auth.admin');
//   // $api->get('artists/{artist_id}','App\Api\v1\Controllers\Artistapi@show')->middleware('auth.admin');
//   // $api->get('cultures/{culture_id}','App\Api\v1\Controllers\Cultureapi@show')->middleware('auth.admin');
//   // $api->get('categories/{category_id}','App\Api\v1\Controllers\Categoryapi@show')->middleware('auth.admin');
//
//
// });

resources/views/media/create.blade.php
@extends('layouts.app')
@section('content')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection

<div class="right_col" role="main">

    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Media / Create </h1>
    </div>

    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('media.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('object_id')) has-error @endif">
                       <label for="object_id-field">Object_id</label>
                    <input type="text" id="object_id-field" name="object_id" class="form-control" value="{{ old("object_id") }}"/>
                       @if($errors->has("object_id"))
                        <span class="help-block">{{ $errors->first("object_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('media_master_id')) has-error @endif">
                       <label for="media_master_id-field">Media_master_id</label>
                    <input type="text" id="media_master_id-field" name="media_master_id" class="form-control" value="{{ old("media_master_id") }}"/>
                       @if($errors->has("media_master_id"))
                        <span class="help-block">{{ $errors->first("media_master_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('display_rend_id')) has-error @endif">
                       <label for="display_rend_id-field">Display_rend_id</label>
                    <input type="text" id="display_rend_id-field" name="display_rend_id" class="form-control" value="{{ old("display_rend_id") }}"/>
                       @if($errors->has("display_rend_id"))
                        <span class="help-block">{{ $errors->first("display_rend_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('public_caption')) has-error @endif">
                       <label for="public_caption-field">Public_caption</label>
                    <input type="text" id="public_caption-field" name="public_caption" class="form-control" value="{{ old("public_caption") }}"/>
                       @if($errors->has("public_caption"))
                        <span class="help-block">{{ $errors->first("public_caption") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('approved_for_web')) has-error @endif">
                       <label for="approved_for_web-field">Approved_for_web</label>
                    <input type="text" id="approved_for_web-field" name="approved_for_web" class="form-control" value="{{ old("approved_for_web") }}"/>
                       @if($errors->has("approved_for_web"))
                        <span class="help-block">{{ $errors->first("approved_for_web") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('rendition_number')) has-error @endif">
                       <label for="rendition_number-field">Rendition_number</label>
                    <input type="text" id="rendition_number-field" name="rendition_number" class="form-control" value="{{ old("rendition_number") }}"/>
                       @if($errors->has("rendition_number"))
                        <span class="help-block">{{ $errors->first("rendition_number") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('sort_number')) has-error @endif">
                       <label for="sort_number-field">Sort_number</label>
                    <input type="text" id="sort_number-field" name="sort_number" class="form-control" value="{{ old("sort_number") }}"/>
                       @if($errors->has("sort_number"))
                        <span class="help-block">{{ $errors->first("sort_number") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('path_id')) has-error @endif">
                       <label for="path_id-field">Path_id</label>
                    <input type="text" id="path_id-field" name="path_id" class="form-control" value="{{ old("path_id") }}"/>
                       @if($errors->has("path_id"))
                        <span class="help-block">{{ $errors->first("path_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('file_name')) has-error @endif">
                       <label for="file_name-field">File_name</label>
                    <input type="text" id="file_name-field" name="file_name" class="form-control" value="{{ old("file_name") }}"/>
                       @if($errors->has("file_name"))
                        <span class="help-block">{{ $errors->first("file_name") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('format_id')) has-error @endif">
                       <label for="format_id-field">Format_id</label>
                    <input type="text" id="format_id-field" name="format_id" class="form-control" value="{{ old("format_id") }}"/>
                       @if($errors->has("format_id"))
                        <span class="help-block">{{ $errors->first("format_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('path')) has-error @endif">
                       <label for="path-field">Path</label>
                    <input type="text" id="path-field" name="path" class="form-control" value="{{ old("path") }}"/>
                       @if($errors->has("path"))
                        <span class="help-block">{{ $errors->first("path") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('physical_path')) has-error @endif">
                       <label for="physical_path-field">Physical_path</label>
                    <input type="text" id="physical_path-field" name="physical_path" class="form-control" value="{{ old("physical_path") }}"/>
                       @if($errors->has("physical_path"))
                        <span class="help-block">{{ $errors->first("physical_path") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('format')) has-error @endif">
                       <label for="format-field">Format</label>
                    <input type="text" id="format-field" name="format" class="form-control" value="{{ old("format") }}"/>
                       @if($errors->has("format"))
                        <span class="help-block">{{ $errors->first("format") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('media_type_id')) has-error @endif">
                       <label for="media_type_id-field">Media_type_id</label>
                    <input type="text" id="media_type_id-field" name="media_type_id" class="form-control" value="{{ old("media_type_id") }}"/>
                       @if($errors->has("media_type_id"))
                        <span class="help-block">{{ $errors->first("media_type_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('media_type')) has-error @endif">
                       <label for="media_type-field">Media_type</label>
                    <input type="text" id="media_type-field" name="media_type" class="form-control" value="{{ old("media_type") }}"/>
                       @if($errors->has("media_type"))
                        <span class="help-block">{{ $errors->first("media_type") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('media_xref_id')) has-error @endif">
                       <label for="media_xref_id-field">Media_xref_id</label>
                    <input type="text" id="media_xref_id-field" name="media_xref_id" class="form-control" value="{{ old("media_xref_id") }}"/>
                       @if($errors->has("media_xref_id"))
                        <span class="help-block">{{ $errors->first("media_xref_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('table_id')) has-error @endif">
                       <label for="table_id-field">Table_id</label>
                    <input type="text" id="table_id-field" name="table_id" class="form-control" value="{{ old("table_id") }}"/>
                       @if($errors->has("table_id"))
                        <span class="help-block">{{ $errors->first("table_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('primary_display')) has-error @endif">
                       <label for="primary_display-field">Primary_display</label>
                    <input type="text" id="primary_display-field" name="primary_display" class="form-control" value="{{ old("primary_display") }}"/>
                       @if($errors->has("primary_display"))
                        <span class="help-block">{{ $errors->first("primary_display") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('db_identifier')) has-error @endif">
                       <label for="db_identifier-field">Db_identifier</label>
                    <input type="text" id="db_identifier-field" name="db_identifier" class="form-control" value="{{ old("db_identifier") }}"/>
                       @if($errors->has("db_identifier"))
                        <span class="help-block">{{ $errors->first("db_identifier") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('media.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
  </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/media/index.blade.php
@extends('layouts.app')
@section('content')

<div class="right_col" role="main">


    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Media
            <a class="btn btn-success pull-right" href="{{ route('media.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>

    <div class="row">
        <div class="col-md-12">
            @if($media->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>S.no</th>
                            <!-- <th>OBJECT_ID</th> -->
                        <!-- <th>MEDIA_MASTER_ID</th> -->
                        <!-- <th>DISPLAY_REND_ID</th> -->
                        <th>PUBLIC_CAPTION</th>
                        <th>APPROVED_FOR_WEB</th>
                        <th>RENDITION_NUMBER</th>
                        <!-- <th>SORT_NUMBER</th> -->
                        <!-- <th>PATH_ID</th> -->
                        <!-- <th>FILE_NAME</th> -->
                        <!-- <th>FORMAT_ID</th> -->
                        <!-- <th>PATH</th> -->
                        <!-- <th>PHYSICAL_PATH</th> -->
                        <!-- <th>FORMAT</th> -->
                        <!-- <th>MEDIA_TYPE_ID</th> -->
                        <!-- <th>MEDIA_TYPE</th> -->
                        <!-- <th>MEDIA_XREF_ID</th> -->
                        <!-- <th>TABLE_ID</th> -->
                        <!-- <th>PRIMARY_DISPLAY</th> -->
                        <th>DB_IDENTIFIER</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($media as $key => $medium)
                            <tr>
                                <td>{{$key}}</td>
                                <!-- <td>{{$medium->object_id}}</td> -->
                    <!-- <td>{{$medium->media_master_id}}</td> -->
                    <!-- <td>{{$medium->display_rend_id}}</td> -->
                    <td>{{$medium->public_caption}}</td>
                    <td>{{$medium->approved_for_web}}</td>
                    <td>{{$medium->rendition_number}}</td>
                    <!-- <td>{{$medium->sort_number}}</td> -->
                    <!-- <td>{{$medium->path_id}}</td> -->
                    <!-- <td>{{$medium->file_name}}</td> -->
                    <!-- <td>{{$medium->format_id}}</td> -->
                    <!-- <td>{{$medium->path}}</td> -->
                    <!-- <td>{{$medium->physical_path}}</td> -->
                    <!-- <td>{{$medium->format}}</td> -->
                    <!-- <td>{{$medium->media_type_id}}</td> -->
                    <!-- <td>{{$medium->media_type}}</td> -->
                    <!-- <td>{{$medium->media_xref_id}}</td> -->
                    <!-- <td>{{$medium->table_id}}</td> -->
                    <!-- <td>{{$medium->primary_display}}</td> -->
                    <td>{{$medium->db_identifier}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('media.show', $medium->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('media.edit', $medium->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('media.destroy', $medium->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $media->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>
</div>
@endsection

resources/views/media/show.blade.php
@extends('layouts.app')
@section('content')

<div class="right_col" role="main">

<div class="page-header">
        <h1>Media / Show #{{$medium->id}}</h1>
        <form action="{{ route('media.destroy', $medium->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('media.edit', $medium->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>

    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="object_id">OBJECT_ID</label>
                     <p class="form-control-static">{{$medium->object_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="media_master_id">MEDIA_MASTER_ID</label>
                     <p class="form-control-static">{{$medium->media_master_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="display_rend_id">DISPLAY_REND_ID</label>
                     <p class="form-control-static">{{$medium->display_rend_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="public_caption">PUBLIC_CAPTION</label>
                     <p class="form-control-static">{{$medium->public_caption}}</p>
                </div>
                    <div class="form-group">
                     <label for="approved_for_web">APPROVED_FOR_WEB</label>
                     <p class="form-control-static">{{$medium->approved_for_web}}</p>
                </div>
                    <div class="form-group">
                     <label for="rendition_number">RENDITION_NUMBER</label>
                     <p class="form-control-static">{{$medium->rendition_number}}</p>
                </div>
                    <div class="form-group">
                     <label for="sort_number">SORT_NUMBER</label>
                     <p class="form-control-static">{{$medium->sort_number}}</p>
                </div>
                    <div class="form-group">
                     <label for="path_id">PATH_ID</label>
                     <p class="form-control-static">{{$medium->path_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="file_name">FILE_NAME</label>
                     <p class="form-control-static">{{$medium->file_name}}</p>
                </div>
                    <div class="form-group">
                     <label for="format_id">FORMAT_ID</label>
                     <p class="form-control-static">{{$medium->format_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="path">PATH</label>
                     <p class="form-control-static">{{$medium->path}}</p>
                </div>
                    <div class="form-group">
                     <label for="physical_path">PHYSICAL_PATH</label>
                     <p class="form-control-static">{{$medium->physical_path}}</p>
                </div>
                    <div class="form-group">
                     <label for="format">FORMAT</label>
                     <p class="form-control-static">{{$medium->format}}</p>
                </div>
                    <div class="form-group">
                     <label for="media_type_id">MEDIA_TYPE_ID</label>
                     <p class="form-control-static">{{$medium->media_type_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="media_type">MEDIA_TYPE</label>
                     <p class="form-control-static">{{$medium->media_type}}</p>
                </div>
                    <div class="form-group">
                     <label for="media_xref_id">MEDIA_XREF_ID</label>
                     <p class="form-control-static">{{$medium->media_xref_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="table_id">TABLE_ID</label>
                     <p class="form-control-static">{{$medium->table_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="primary_display">PRIMARY_DISPLAY</label>
                     <p class="form-control-static">{{$medium->primary_display}}</p>
                </div>
                    <div class="form-group">
                     <label for="db_identifier">DB_IDENTIFIER</label>
                     <p class="form-control-static">{{$medium->db_identifier}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('media.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>
  </div>

@endsection