app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

$api = app('Dingo\Api\Routing\Router');
//
// Route::get('/', function () {
//     return view('welcome');
// });

// Route::auth();

// Authentication Routes...
// Route::post('login', 'Auth\AuthController@login');
Route::get('logout', 'LoginController@logout');
Route::get('login', 'LoginController@getLogin');
Route::post('login', [ 'as' => 'login', 'uses' => 'LoginController@validateCredentials']);

// Route::post('login', 'LoginController@validateCredentials');

// Registration Routes...
// Route::get('register', 'Auth\AuthController@showRegistrationForm');
// Route::post('register', 'Auth\AuthController@register');

// Password Reset Routes...
Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
Route::post('password/reset', 'Auth\PasswordController@reset');

// Web Routes //

Route::get('/', 'Dashboard@index');

Route::get('categories/posterchange', 'CategoryController@posterchange');
Route::get('artists/posterchange', "ArtistController@posterchange");
Route::resource("categories","CategoryController",
                ['only' => ['index', 'show']]);
Route::resource("artists","ArtistController",
                ['only' => ['index', 'show']]);
Route::resource("cultures","CultureController",
                ['only' => ['index', 'show']]);
Route::resource("favourites","FavouriteController");
Route::resource("media","MediumController",
                ['only' => ['index', 'show']]);
// Route::resource("objectcategories","ObjectcategoryController");
// Route::resource("objectartists","ObjectartistController");
Route::resource("galleries","ObjectController",
                ['only' => ['index', 'show']]);


// Route::get('map', 'MappingController@map');
// Route::resource("main_categories","MainCategoryController");
Route::resource("m_main_categories","MMainCategoryController"); // Add this line in routes.php
Route::get('appheadings/postsequesnce', 'AppheadingController@postsequesnce');
Route::get('appheadings/appheadings', 'AppheadingController@appheadings');
Route::post('appheadings/updatedetails', 'AppheadingController@updatedetails');
Route::resource("appheadings","AppheadingController");

// Route::get('artist/posterchange', 'ArtistController@posterchange');
// Route::get('artist/posterchange', 'ArtistController@posterchange');
// Route::resource("server_details","ServerDetailController");
// Route::resource("galleries","GalleryController");
// Route::resource("main_categories","MainCategoryController");
// Route::resource("cultures","CultureController");
// Route::resource("categories","CategoryController");
// Route::resource("app_details","AppDetailController");
// Route::resource("artists","ArtistController");
// Route::resource("favorites","FavoriteController");
// Route::resource("basic_auths","BasicAuthController");
// Route::resource("post_categories","PostCategoryController");
//
// Route::get("cultures","PostCategoryController@cultures_index");
// Route::get("artists","PostCategoryController@artists_index");
// Route::get("categories","PostCategoryController@categories_index");



// API Routes //

// $api->version('v1', function ($api) {
//
//   $api->get('maincategory/','App\Api\v1\Controllers\MainCategoryapi@index')->middleware('auth.admin');
//   $api->get('subcategory/data_by_id','App\Api\v1\Controllers\SubCategoryapi@all_by_id')->middleware('auth.admin');
//   $api->get('galleries','App\Api\v1\Controllers\Galleryapi@index')->middleware('auth.admin');
//   $api->get('galleries/by_subcategory','App\Api\v1\Controllers\SubCategoryapi@subcategories_gallery_by_id')->middleware('auth.admin');
//   $api->get('galleries/gallery_search','App\Api\v1\Controllers\Galleryapi@gallery_search')->middleware('auth.admin');
//   $api->get('galleries/all_subcategory','App\Api\v1\Controllers\Galleryapi@all_subcategory')->middleware('auth.admin');
//   $api->post('favorites','App\Api\v1\Controllers\Favoriteapi@store')->middleware('auth.admin');
//   $api->get('favorites/userfavorite','App\Api\v1\Controllers\Favoriteapi@user_favorite')->middleware('auth.admin');
//   $api->post('users/login','App\Api\v1\Controllers\Userapi@login')->middleware('auth.admin');
//   $api->get('users/logout','App\Api\v1\Controllers\Userapi@logout')->middleware('auth.admin');
//   $api->post('users/','App\Api\v1\Controllers\Userapi@storeapi')->middleware('auth.admin');
//
//
//
//
//   // $api->post('galleries','App\Api\v1\Controllers\Galleryapi@store')->middleware('auth.admin');
//   // $api->get('galleries/by_artist','App\Api\v1\Controllers\Galleryapi@by_artist')->middleware('auth.admin');
//   // $api->get('galleries/by_category','App\Api\v1\Controllers\Galleryapi@by_category')->middleware('auth.admin');
//   // $api->get('galleries/by_culture','App\Api\v1\Controllers\Galleryapi@by_culture')->middleware('auth.admin');
//
//
//
//
//   $api->get('galleries/{gallery_id}','App\Api\v1\Controllers\Galleryapi@show')->middleware('auth.admin');
//   $api->get('subcategory/{subcategory_id}','App\Api\v1\Controllers\SubCategoryapi@show')->middleware('auth.admin');
//   // $api->get('artists/','App\Api\v1\Controllers\Artistapi@index')->middleware('auth.admin');
//   // $api->get('cultures/','App\Api\v1\Controllers\Cultureapi@index')->middleware('auth.admin');
//   // $api->get('categories/','App\Api\v1\Controllers\Categoryapi@index')->middleware('auth.admin');
//   // $api->get('artists/{artist_id}','App\Api\v1\Controllers\Artistapi@show')->middleware('auth.admin');
//   // $api->get('cultures/{culture_id}','App\Api\v1\Controllers\Cultureapi@show')->middleware('auth.admin');
//   // $api->get('categories/{category_id}','App\Api\v1\Controllers\Categoryapi@show')->middleware('auth.admin');
//
//
// });

app/MMainCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MMainCategory extends Model
{
    //
}

app/Http/Controllers/MMainCategoryController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\MMainCategory;
use Illuminate\Http\Request;
use Image;
use Session;
use Illuminate\Support\Facades\Redirect;


class MMainCategoryController extends Controller {

/**
 * Display a listing of the resource.
 *
 * @return Response
 */

 public function __construct()
{
 if(!Session::has('user'))
 {
		 Redirect::to('login')->send();
 }
}

public function index()
{
	$m_main_categories = MMainCategory::orderBy('id', 'asc')->paginate(10);
  // return compact('m_main_categories');die;
	return view('m_main_categories.index', compact('m_main_categories'));
}

/**
 * Show the form for creating a new resource.
 *
 * @return Response
 */
public function create()
{
	return view('m_main_categories.create');
}

/**
 * Store a newly created resource in storage.
 *
 * @param Request $request
 * @return Response
 */
public function store(Request $request)
{
	$main_category = new MMainCategory();
	$main_category->title = $request->input("title");
	$main_category->text_color = $request->input("text_color");
	$main_category->background_color = $request->input("background_color");
	$file = $request->file('image');
	$imageName = time().'.'.
	$request->file('image')->getClientOriginalExtension();
	$request->file('image')->move(base_path() . '/public/uploads/main_category/', $imageName);
	$image = Image::make(sprintf('uploads/main_category/%s', $imageName))->resize(600, 600)->save();
	$main_category->image_name = $imageName;

	$main_category->save();

	return redirect()->route('m_main_categories.index')->with('message', 'Item created successfully.');
}

/**
 * Display the specified resource.
 *
 * @param  int  $id
 * @return Response
 */
public function show($id)
{
	$main_category = MMainCategory::findOrFail($id);

	return view('m_main_categories.show', compact('main_category'));
}

/**
 * Show the form for editing the specified resource.
 *
 * @param  int  $id
 * @return Response
 */
public function edit($id)
{
	$main_category = MMainCategory::findOrFail($id);

	return view('m_main_categories.edit', compact('main_category'));
}

/**
 * Update the specified resource in storage.
 *
 * @param  int  $id
 * @param Request $request
 * @return Response
 */
public function update(Request $request, $id)
{
	$main_category = MMainCategory::findOrFail($id);

	$main_category->title = $request->input("title");
	$main_category->text_color = $request->input("text_color");
	$main_category->background_color = $request->input("background_color");
	$file = $request->file('image');
	if(!empty($file)){
		$imageName = time().'.'.
		$request->file('image')->getClientOriginalExtension();
		$request->file('image')->move(base_path() . '/public/uploads/main_category/', $imageName);
		$image = Image::make(sprintf('uploads/main_category/%s', $imageName))->resize(600, 600)->save();
		$main_category->image_name = $imageName;
	}

	$main_category->save();

	return redirect()->route('m_main_categories.index')->with('message', 'Item updated successfully.');
}

/**
 * Remove the specified resource from storage.
 *
 * @param  int  $id
 * @return Response
 */
public function destroy($id)
{
	$main_category = MMainCategory::findOrFail($id);
	$main_category->delete();

	return redirect()->route('m_main_categories.index')->with('message', 'Item deleted successfully.');
}

}

resources/views/m_main_categories/create.blade.php
@extends('layouts.app')
@section('content')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection

@include('error')

<div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="page-header clearfix">
                  <h1>
                      <i class="glyphicon glyphicon-align-justify"></i> Main Category Create
                      <a class="btn btn-success pull-right" href="{{ route('m_main_categories.index') }}"><i class="glyphicon glyphicon-plus"></i> Index</a>
                  </h1>

              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <!-- <h2>L<small>ist</small></h2> -->
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <!-- <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li> -->
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content" style="display: block;">


            <form action="{{ route('m_main_categories.store') }}" method="POST" enctype='multipart/form-data' class="form-horizontal form-label-left">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('title')) has-error @endif">
                       <label class= "control-label col-md-3 col-sm-3 col-xs-12" for="title-field">Title</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="title-field" name="title" class="form-control" value="{{ old("title") }}"/>
                  </div>
                       @if($errors->has("title"))
                        <span class="help-block">{{ $errors->first("title") }}</span>
                       @endif
                    </div>

                    <div class="form-group @if($errors->has('text_color')) has-error @endif">
                       <label class= "control-label col-md-3 col-sm-3 col-xs-12"  for="text_color-field">Text Color</label>
                       <div  id="cp1" class="col-md-6 col-sm-6 col-xs-12 input-group colorpicker-component">
                    <input type="text" id="text_color-field" name="text_color" class="form-control" value="{{ old("text_color") }}"/><span class="input-group-addon"><i></i></span>
                       @if($errors->has("text_color"))
                        <span class="help-block">{{ $errors->first("text_color") }}</span>
                       @endif
                    </div>
                  </div>

                    <div class="form-group @if($errors->has('background_color')) has-error @endif">
                       <label class= "control-label col-md-3 col-sm-3 col-xs-12"  for="text_color-field">Background Color</label>
                       <div id="cp2" class="col-md-6 col-sm-6 col-xs-12 input-group colorpicker-component">
                    <input type="text" id="background_color-field" name="background_color" class="form-control" value="{{ old("background_color") }}"/><span class="input-group-addon"><i></i></span>
                       @if($errors->has("background_color"))
                        <span class="help-block">{{ $errors->first("background_color") }}</span>
                       @endif
                    </div>
                  </div>

                    <div class="form-group @if($errors->has('image')) has-error @endif">
                       <label class= "control-label col-md-3 col-sm-3 col-xs-12" for="dimensions-field">Image</label>
                       <div class="col-md-6 col-sm-6 col-xs-12">

                       <input type="file" id="image-field" name="image" class="form-control" value="{{ old("image") }}"/>
                       @if($errors->has("image"))
                        <span class="help-block">{{ $errors->first("image") }}</span>
                       @endif
                    </div>
                  </div>



                  <div class="ln_solid"></div>
                  <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('m_main_categories.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                  </div>
                </div>
            </form>

        </div>
    </div>
  </div>
</div>
</div>
</div>


<script src="{{ asset("js/bootstrap-colorpicker.min.js") }}"></script>
<!-- Bootstrap -->
<link href="{{ asset("css/bootstrap-colorpicker.min.css") }}" rel="stylesheet">

<!-- <script src="{{ asset("js/bootstrap-colorpicker.min.js") }}"></script> -->
<!-- Bootstrap -->
<!-- <link href="{{ asset("css/bootstrap-colorpicker.min.css") }}" rel="stylesheet"> -->

<script>
$(function() {
  $('#cp1').colorpicker();
});
</script>

<script>
$(function() {
  $('#cp2').colorpicker();
});
</script>

@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/m_main_categories/edit.blade.php
@extends('layouts.app')
@section('content')
@section('css')

  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection


@include('error')

<div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="page-header clearfix">
                  <h1>
                      <i class="glyphicon glyphicon-edit"></i> Main Category Update
                      <a class="btn btn-success pull-right" href="{{ route('m_main_categories.index') }}"><i class="glyphicon glyphicon-plus"></i> Index</a>

                      <!-- <h1><i class="glyphicon glyphicon-edit"></i> MainCategories / Edit #{{$main_category->id}}</h1> -->
                  </h1>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <!-- <h2>L<small>ist</small></h2> -->
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <!-- <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li> -->
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content" style="display: block;">

            <form action="{{ route('m_main_categories.update', $main_category->id) }}" method="POST" enctype='multipart/form-data' class="form-horizontal form-label-left">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('title')) has-error @endif">
                       <label class= "control-label col-md-3 col-sm-3 col-xs-12" for="title-field">Title</label>
                       <div  class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="title-field" name="title" class="form-control" value="{{ is_null(old("title")) ? $main_category->title : old("title") }}"/>
                       @if($errors->has("title"))
                        <span class="help-block">{{ $errors->first("title") }}</span>
                       @endif
                     </div>
                    </div>
              <div class="form-group @if($errors->has('text_color')) has-error @endif">
                     <label class= "control-label col-md-3 col-sm-3 col-xs-12" for="background_color-field">Text Color</label>
                     <div id="cp1" class="col-md-6 col-sm-6 col-xs-12 input-group colorpicker-component">
                  <input type="text" id="text_color-field" name="text_color" class="form-control" value="{{ is_null(old("text_color")) ? $main_category->text_color : old("text_color") }}"/><span class="input-group-addon"><i></i></span>
                     @if($errors->has("text_color"))
                      <span class="help-block">{{ $errors->first("text_color") }}</span>
                     @endif
                   </div>
                  </div>
                  <div class="form-group @if($errors->has('background_color')) has-error @endif">
                         <label class= "control-label col-md-3 col-sm-3 col-xs-12" for="background_color-field">Background Color</label>
                         <div id="cp2" class="col-md-6 col-sm-6 col-xs-12 input-group colorpicker-component">
                      <input type="text" id="background_color-field" name="background_color" class="form-control" value="{{ is_null(old("background_color")) ? $main_category->background_color : old("background_color") }}"/><span class="input-group-addon"><i></i></span>
                         @if($errors->has("background_color"))
                          <span class="help-block">{{ $errors->first("background_color") }}</span>
                         @endif
                      </div>
                    </div>

                    <div class="form-group @if($errors->has('image')) has-error @endif">
                       <label class= "control-label col-md-3 col-sm-3 col-xs-12" for="dimensions-field">Image</label>
                       <div class="col-md-6 col-sm-6 col-xs-12">
                       @if($main_category->image_name !="")
                        <img src="{{ asset( '/uploads/main_category').'/'.$main_category->image_name }}" class="image-class" id= "img-class" style="width:60px;"/>
                       @endif
                       <input type="file" id="image-field" name="image" class="form-control" value="{{ old("image") }}"/>
                       @if($errors->has("image"))
                        <span class="help-block">{{ $errors->first("image") }}</span>
                       @endif
                    </div>
                  </div>

                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('m_main_categories.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
  </div>
</div>
</div>
</div>

<script src="{{ asset("js/bootstrap-colorpicker.min.js") }}"></script>
<!-- Bootstrap -->
<link href="{{ asset("css/bootstrap-colorpicker.min.css") }}" rel="stylesheet">
  <!-- <script src="{{ asset("js/bootstrap-colorpicker.min.js") }}"></script> -->
  <!-- Bootstrap -->
  <!-- <link href="{{ asset("css/bootstrap-colorpicker.min.css") }}" rel="stylesheet"> -->

  <script>
  $(function() {
    $('#cp1').colorpicker();
  });
  </script>

  <script>
  $(function() {
    $('#cp2').colorpicker();
  });
  </script>

@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/m_main_categories/show.blade.php
@extends('layouts.app')
@section('content')
<div class="right_col" role="main">
  <div class="page-title">
<div class="page-header">
        <h1><i class="glyphicon glyphicon-align-justify"></i> MainCategories / Show

         <!--  <form action="{{ route('m_main_categories.destroy', $main_category->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
              <input type="hidden" name="_method" value="DELETE">
              <input type="hidden" name="_token" value="{{ csrf_token() }}">
              <div class="btn-group pull-right" role="group" aria-label="...">
                  <a class="btn btn-warning btn-group" role="group" href="{{ route('m_main_categories.edit', $main_category->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                  <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
              </div>
          </form> -->
        </h1>

    </div>

    </div>


    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <form action="#">
                <div class="col-md-4">
                  <div style="width:530px; margin:0 auto; background:#eee; padding:10px;">
                  <ul style="margin:0; padding:0; list-style:none;">
                      <li style="background:{{$main_category->background_color}}; height:210px; text-align:center; font-family:arial; color:{{$main_category->text_color}}; width:249px; vertical-align:top; display:inline-block; box-shadow:1px 3px 2px #a1a1a1 <span class='hexPreview' style='background-color: #a1a1a1'>&nbsp;</span>; margin-right:3px; margin-bottom:10px;">
                        <div style="width:249px; height:210px; display:table-cell; vertical-align:middle; font-size:40px; text-align:center;">{{$main_category->title}}</div>
                      </li>
                      <li style="height:210px; box-shadow:1px 3px 2px #a1a1a1 <span class='hexPreview' style='background-color: #a1a1a1'>&nbsp;</span>; text-align:center; font-family:arial; color:#fff;  display:inline-block; vertical-align:top; width:249px; margin-bottom:10px;"><img src="{{ asset( 'uploads/main_category/' )."/".$main_category->image_name }}" style='width:249px; height:210px;' alt=""/></li>
                  </ul>
                  </div>
                </div>
            </form>
             <div class="back-btn">
            <a class="btn btn-link" href="{{ route('m_main_categories.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
          </div>
          </div>
        </div>
    </div>




  </div>







@endsection